#+title: Course Overview
#+author: Matt Brigida, Ph.D.
#+SETUPFILE: https://fniessen.github.io/org-html-themes/setup/theme-readtheorg.setup

We are going to study a series of topics in this course which may appear unrelated to the student.  In fact, each topic is a step to our ultimate goal of being able to *value a project or contract* (or equivalently a firm which is simply a collection of projects).

#+BEGIN_QUOTE
The value of a project is the present value of all expected future cash flows from the project discounted at a risk-appropriate rate.
#+END_QUOTE

So to value a project we need to (1) calculate relevant cash flows, and (2) move them around in time to calculate present values. We then need to have an understanding of what we mean by risk, and how to calculate the risk in a given asset.

This is our goal in this course, and everything that follows is required knowledge to calculate this value.  This has an important implication, `every topic will be used later, so you can't understand later chapters without learning the former`.

+ Chapter 1: We first learn about the corporate form, and its benefits and costs.
+ Chapter 2: We review financial statements.  We do this because we will use financial statements to calculate cash flow.  That is we are not interested in the financial statements themselves, and what accountants are attempting to do, we merely want to use them to get cash flow.
+ Chapter 3: We learn to calculate the cash flows which will be used in the valuation.
+ Chapter 4 (Time-Value-of-Money): We learn how to move cash flows to different points in time.  In this chapter we basically create a set of tools that can be applied in later situations where we need to move cash flows in time. It is important that you don't memorize formulas, but rather understand what they are doing.  Later in the course students will often ask me "what is the formula for this", and I'll answer that there are many.  There is not one formula for a particular task, there is a particular skill set which will allow you to use many different formulas to do the same thing.
+ Chapter 5 (Time-Value-of-Money): We learn how to move multiple cash flows in time---this is used in common contracts such as mortgages and auto loans.  We also learn about compounding which is important in understanding how interest rates will be quoted.
+ Chapter 6: Assuming we know the discount rate (which is a function of risk) we'll use our time-value-of-money tools to calculate the price of a bond given the yield, or the yield given the price.  We'll also learn about the bond contract.
+ Chapter 7: We learn about equity (stock) and methods for its valuation
+ Chapter 8: Investment decision rules.
+ Chapter 9: Making capital investment decisions.  
+ Chapter 10 and 11: We learn to measure an asset's risk.
+ Chapter 12 and 13: We use our measure of asset risk to determine the discount rate appropriate to the firm's assets.  We also use this to investigate the capital structure of the firm.

Lastly, let me reiterate the quote from R.W. Hamming in the syllabus:

#+BEGIN_QUOTE
"The purpose of computing is insight not numbers".
#+END_QUOTE

Our calculations are derived from underlying factors, and as these factors change so does our calculation.  There is very little in this course which can simply be memorized. What we aspire to is an understanding of the output we are producing and how it will be used, and how our methods relate to the inputs of our calculation.  Note I mentioned the output first---you need to know what you want before you think about your inputs or methods.

And always remember, our output is used to make a business decision. We don't do calculations to fill time.  So producing a number without knowing how to use it is worthless.  
